vlib work
vlog  Decoder.v
vlog  Maximum_Calculator.v
vlog  Decoder_block.v
vlog  tabla_spwm_g1.v
vlog  Decoder_block1.v
vlog  tabla_spwm_g2.v
vlog  Decoder_block2.v
vlog  tabla_spwm_g4.v
vlog  SPWM_3mod_hdl.v
