/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx_hal.h"

SPI_HandleTypeDef hspi1;
DMA_HandleTypeDef hdma_spi1_tx;

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_SPI1_Init(void);
static void Error_Handler(void);

// Ejemplo de Lookup Table (LUT)
uint16_t lut[] = {
    0x1111, 0x2222, 0x3333, 0x4444,
    0x5555, 0x6666, 0x7777, 0x8888};

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_SPI1_Init();

    uint16_t length = sizeof(lut) / sizeof(lut[0]);

    while (1)
    {
        // Esperar a que NSS baje (el maestro selecciona al esclavo)
        // Como NSS está configurado como entrada, la leemos:
        if (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_15) == GPIO_PIN_RESET)
        {
            // NSS está en bajo, el maestro solicita datos.
            // Llamamos a HAL_SPI_Transmit bloqueante.
            // Como DataSize=16 bits, cada elemento del LUT son 2 bytes.
            // HAL_SPI_Transmit recibe Size en "number of data" de 16 bits
            // si DataSize=16, el parámetro Size se cuenta en "halves" o "words" según doc.
            // Nota: En la HAL de F1, el Size se cuenta en unidades del DataSize. Así que
            // pasar 'length' es correcto, no length*2.

            if (HAL_SPI_Transmit(&hspi1, (uint8_t *)lut, length, HAL_MAX_DELAY) != HAL_OK)
            {
                // Manejar error
                Error_Handler();
            }

            // Esperamos a que NSS vuelva a alto para el próximo requerimiento
            while (HAL_GPIO_ReadPin(GPIOB, GPIO_PIN_15) == GPIO_PIN_RESET)
            {
                // Esperando al maestro que libere NSS
            }
        }
    }
}

static void MX_SPI1_Init(void)
{
    hspi1.Instance = SPI1;
    hspi1.Init.Mode = SPI_MODE_SLAVE;           // Modo esclavo
    hspi1.Init.Direction = SPI_DIRECTION_1LINE; // Solo envío, si se desea full duplex usar SPI_DIRECTION_2LINES
    hspi1.Init.DataSize = SPI_DATASIZE_16BIT;   // 16 bits
    hspi1.Init.CLKPolarity = SPI_POLARITY_LOW;
    hspi1.Init.CLKPhase = SPI_PHASE_1EDGE;
    hspi1.Init.NSS = SPI_NSS_HARD_INPUT; // NSS por hardware, pin NSS (PA4)
    hspi1.Init.FirstBit = SPI_FIRSTBIT_MSB;
    hspi1.Init.TIMode = SPI_TIMODE_DISABLE;
    hspi1.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
    hspi1.Init.CRCPolynomial = 10;
    if (HAL_SPI_Init(&hspi1) != HAL_OK)
    {
        Error_Handler();
    }
}

static void MX_DMA_Init(void)
{
    // __HAL_RCC_DMA1_CLK_ENABLE();

    // Configurar DMA para SPI1_TX
    // hdma_spi1_tx.Instance = DMA1_Channel3;
    // hdma_spi1_tx.Init.Direction = DMA_MEMORY_TO_PERIPH;
    // hdma_spi1_tx.Init.PeriphInc = DMA_PINC_DISABLE;
    // hdma_spi1_tx.Init.MemInc = DMA_MINC_ENABLE;
    // hdma_spi1_tx.Init.PeriphDataAlignment = DMA_PDATAALIGN_HALFWORD;
    // hdma_spi1_tx.Init.MemDataAlignment = DMA_MDATAALIGN_HALFWORD;
    // hdma_spi1_tx.Init.Mode = DMA_NORMAL; // o Circular si quieres repetir continuamente
    // hdma_spi1_tx.Init.Priority = DMA_PRIORITY_HIGH;
    // if (HAL_DMA_Init(&hdma_spi1_tx) != HAL_OK)
    // {
    //     Error_Handler();
    // }

    // // Asociar el DMA al SPI
    // __HAL_LINKDMA(&hspi1, hdmatx, hdma_spi1_tx);
}

static void MX_GPIO_Init(void)
{
    /* Habilita el reloj del AFIO antes de hacer el remapeo */
    __HAL_RCC_AFIO_CLK_ENABLE();

    /* Activa el remapeo de SPI1 */
    __HAL_AFIO_REMAP_SPI1_ENABLE();

    /* Ahora configura los GPIO del SPI remapeado */
    // Asegúrate de habilitar el reloj de los puertos correspondientes antes
    __HAL_RCC_GPIOB_CLK_ENABLE();
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    // SCK - PB3
    GPIO_InitStruct.Pin = GPIO_PIN_3;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    // MISO - PB4
    GPIO_InitStruct.Pin = GPIO_PIN_4;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    // MOSI - PB5
    GPIO_InitStruct.Pin = GPIO_PIN_5;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    // NSS (opcional) - PA15 si lo necesitas
    __HAL_RCC_GPIOA_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_15;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
}

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // Ajustar según tu configuración. Aquí un ejemplo a 72MHz usando HSE a 8MHz:
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
    {
        Error_Handler();
    }
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
    {
        Error_Handler();
    }
}

void Error_Handler(void)
{
    while (1)
    {
        // Quedarse aquí en caso de error
    }
}

// Opcional: Callback al terminar la transmisión por DMA
void HAL_SPI_TxCpltCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi->Instance == SPI1)
    {
        // Se completó la transmisión de la LUT
        // Aquí puedes reiniciar la transmisión si quieres que se repita en la próxima activación de NSS.
        HAL_SPI_Transmit_DMA(&hspi1, (uint8_t *)lut, sizeof(lut) / sizeof(lut[0]));
    }
}
